#!/usr/bin/env node

var minimist = require('minimist')
var browserify = require('browserify')
var hyperstream = require('hyperstream')
var replace = require('replacestream')
var fs = require('fs')
var spawn = require('child_process').spawn

var args = process.argv.slice(2)

var options = minimist(args)

process.stdin
  .pipe(fs.createWriteStream('./browser/fsj.json'))
  .on('finish', function(err) {
    var b = browserify(['./browser/index.js'])
    var css = fs.createReadStream('./browser/style.css')
    var bundle = b.bundle().pipe(replace('</script>', '<\\/script>'))

    fs.createReadStream('./browser/index.html')
      .pipe(hyperstream({
        '#style': css,
        '#js': bundle
      }))
      .pipe(process.stdout)
  })

function log(data) {
  console.log(data.toString())
}
