#!/usr/bin/env node

var browserify = require('browserify')
var hyperstream = require('hyperstream')
var replace = require('replacestream')
var fs = require('fs')
var spawn = require('child_process').spawn

var args = process.argv.slice(2)

process.stdin
  .pipe(fs.createWriteStream(__dirname + '/browser/fsj.json'))
  .on('finish', function(err) {
    var b = browserify([__dirname + '/browser/go.js'])
    var css = fs.createReadStream(__dirname + '/browser/style.css')
    var bundle = b.bundle().pipe(replace('</script>', '<\\/script>'))

    fs.createReadStream(__dirname + '/browser/index.html')
      .pipe(hyperstream({
        '#style': css,
        '#js': bundle
      }))
      .pipe(process.stdout)
  })

function log(data) {
  console.log(data.toString())
}
